### ISSUE TITLE
crash at processing gene calls

### ISSUE THREAD

**Issue by xvazquezc** [carolzhou/multiPhATE2#17]
Hi,
I was trying to run the program with primary gene calls set to something different to `prodigal` (as per the sample config file), but I get errors. So far I've tested `phanotate`, `consensus` and `superset`, all of them producing the same kind of error. Setting the value to `prodigal` works ok though.

This is an example of the error:
```
phate_sequenceAnnotation_main says, Processing gene calls...
phate_sequenceAnnotation_main says, geneCallInfo {'primaryCalls': 'consensus', 'primaryCallsPathFile': '/share/bioinfo/z3382651/multiPhATE2/PipelineOutput/Ps15_phate/consensus.cgc', 'genomeName': 'Ps15'} infile_primaryCalls /share/bioinfo/z3382651/multiPhATE2/PipelineOutput/Ps15_phate/consensus.cgc contigSeqLen_hash {'NODE_1_length_161405_cov_44577217_1-161405/161405': 161405}
Translate nucleic acid sequences
Warning: Sequence 'fasta::/share/bioinfo/z3382651/multiPhATE2/PipelineOutput/Ps15_phate/tempGeneFile:NODE_1_length_161405_cov_44.577217_consensus_1_geneCall' has zero length, ignored
Error: Unable to read sequence '/share/bioinfo/z3382651/multiPhATE2/PipelineOutput/Ps15_phate/tempGeneFile'
Died: transeq terminated: Bad value for '-sequence' and no prompt
Traceback (most recent call last):
  File "/share/bioinfo/z3382651/multiPhATE2/SequenceAnnotation/phate_sequenceAnnotation_main.py", line 1038, in <module>
    myGenome.processGeneCalls(geneCallInfo,PRIMARY_CALLS_FILE_H)
  File "/share/bioinfo/z3382651/multiPhATE2/SequenceAnnotation/phate_genomeSequence.py", line 412, in processGeneCalls
    newProtein.sequence = self.translateGene(newGene)
  File "/share/bioinfo/z3382651/multiPhATE2/SequenceAnnotation/phate_genomeSequence.py", line 730, in translateGene
    PROT_H = open(tempProtFile,"r")
FileNotFoundError: [Errno 2] No such file or directory: '/share/bioinfo/z3382651/multiPhATE2/PipelineOutput/Ps15_phate/tempProtFile'
phate_runPipeline says, Sequence annotation processing is complete.
```

**Comment by carolzhou** [comment]
Please send me your input genome file and your configuration file.

**Comment by xvazquezc** [comment]
Can you provide an email address? The genome hasn't been published yet.

**Comment by carolzhou** [comment]
multiphate@gmail.com

**Comment by carolzhou** [comment]
This might be a problem with non-alphanumeric characters in fasta headers. Some 3rd party codes will fail when encountering odd characters. Try cleaning your input genome fasta file using the cleanHeaders.py script in the Utility/ folder. Let me know if that does not fix the problem.

**Comment by carolzhou** [comment]
I am closing this issue. Let me know if you have any additional difficulties using multiPhATE2.

**Comment by xvazquezc** [comment]
Just to confirm. Simplifying the fasta header of the input genome allows to enter the annotation phase without issues.
Thanks.

**Comment by carolzhou** [comment]
Thank you for letting me know.
