### ISSUE TITLE
need to check for empty lines in processProdigal

### ISSUE THREAD

**Issue by tsp-kucbd** [carolzhou/multiPhATE2#33]
prodigal sometimes add an empty line in its gff output, which then will choke the processProdigal parser. (tested on macOS Catalina)
```
phate_runPipeline says, Checking files...
phate_runPipeline says, Configuration complete.
phate_runPipeline says, Preparing to run genecall module...
phate_runPipeline says, Calling the gene-call module.
phate_genecallPhage says, running Prodigal.
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.
-------------------------------------
Request:  Metagenomic, Phase:  Training
Initializing training files...done!
-------------------------------------
Request:  Metagenomic, Phase:  Gene Finding
Finding genes in sequence #1 (38454 bp)...done!
Traceback (most recent call last):
  File "/projects/misc/multiPhATE2/GeneCalling/phate_genecallPhage.py", line 402, in <module>
    processProdigal(line)
  File "/projects/misc/multiPhATE2/GeneCalling/phate_genecallPhage.py", line 206, in processProdigal
    method = lineSplit[1]
IndexError: list index out of range
```
Dirty solution
```python
def processProdigal(line):
    if not line.startswith("#"):
        lineSplit = line.split("\t")
        if len(lineSplit) < 6: return  # <<<<<<<<< catch and return
        
        contig = lineSplit[0]
        method = lineSplit[1]
        start  = lineSplit[3]
        stop   = lineSplit[4]
        score  = lineSplit[5]
        strand = lineSplit[6]

        ID = getProdigalId(lineSplit[8])

        if PHATE_MESSAGES:
            print("phate_genecallPhage says,  ID=",ID,"method=",method,"contig=",contig,"start/stop=",start,'/',stop,"strand=",strand,"score=",score)
        geneCall(ID, method, contig, start, stop, strand, score)
        callCounts['prodigal'] += 1
```

**Comment by carolzhou** [comment]
Great catch! This is one I haven't seen before, even after having run Prodigal on many genomes. Would you happen to have a sample genome that causes Prodigal to output the blank lines? I will repair the code to avoid this problem in future. Thanks!
